= Lecture-Notes-3-insy-praxis
Peter Klose
1.0.0, yyyy-mm-dd: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== INSY Praxis

=== Create Tables

Syntax:

[source,sql]
----
create table table_name (
                 column_name data_type [default expression] [column integrity rule]
      [, column_name ....,
                  ....]
  );
----

==== Bsp: Erzeugen der Tabelle Players

[source,sql]
----
create table Players
(PlayerNo number(4) not null,
 Name varchar2(15),
 date_of_birth date,
 leagueno varchar2(4));
----
//Abb4
//Abb5
=== Copying tables
//Abb7

=== Dropping Tables
//Abb9

==== Ändern von Spalten

==== Add Column

==== Synonyms für Tabellennamen

=== Das SELECT Statement

==== Literals

==== Systemvariablen

Datumsformat ausgeben

[source,sql]
----
select sysdate from dual;
select user from dual;
----

==== Expressions (Ausdrücke)

Nummerische Ausdrücke

+-*/mod

[source,sql]
----
select amount+2 from penalties;
select 3+4*2 from dual;
select mod(13,5) from dual;
----

Alphanummerische Ausdrücke (CONCAT)

[source,sql]
----
select 'Hello World' || 'in HTL' from dual;
select concat('Hello World','in HTL') from dual;
-- Abb 13
select upper(substr('Oracle Substring',1,6)) from dual;
----

== 2021.12.21

=== NULL Operator

//Abb 20
Wichtig immer mit IS [NOT] NULL abfragen = oder != funktioniert nicht

|===
|If a is: |Condition |Evaluates to:

|10
|a IS NULL
|FALSE

|10
|a IS NOT NULL
|TRUE

|NULL
|a IS NULL
|TRUE

|NULL
|a IS NOT NULL
|FALSE

|10
|a = NULL
|UNKNOWN

|10
|a != NULL
|UNKNOWN

|NULL
|a = NULL
|UNKNOWN

|NULL
|a != NULL
|UNKNOWN

|NULL
|a = 10
|UNKNOWN

|NULL
|a != 10
|UNKNOWN
|===

==== Bsp: Ausgabe der Turnierspieler

[source,sql]
----
select * from players where leagueno IS NOT NULL;
----

=== IN Operator mit Subquery

Vorteile:

* Aktualität

==== Bsp: Ausgabe der Spieler, die mindestens eine Straft, erhalten haben

Variante 1 ohne Subquery (FALSCH)

[source,sql]
----
select distinct playerno from penalties;
select * from players where playerno in (6,8,27,44,104);
----

Variante 2 mit Subquery (RICHTIG)

[source,sql]
----
select * from players where playerno in (select playerno from penalties);
--in der Klammer mit oder ohne distinct
----

==== Bsp: Ausgabe der Playerno, name und initials der Spieler, die mindestens ein match gewonnen haben

[source,sql]
----
select playerno,name,initials from players where playerno in (select playerno from matches where won >= 1);
----

INS_SQL-Uebun3.sql

=== Vergleichsoperator mit Subquery

Syntax

[source,sql]
----
expression comparison_operator (subquery);
----

Der Vergleich mit Subqueries, darf das Subquery nur 1 Zeile leifern.

==== Bsp: Ausgabe der Playerno und name der Spieler, die älter als R.Parmenter sind?

[source,sql]
----
select playerno, name from players where year_of_birth < (select year_of_birth from players where name like 'Parmenter' and initials like 'R');
----


== 2021.12.22

=== Die Operatoren ALL und ANY

Syntax:

[source,sql]
----
expression comparison_operator ALL (subquery);
expression comparison_operator ANY (subquery);
----

expression comparison_operator ALL (subquery)
expression comparison_operator ANY (subquery)

==== Hinweis:

Ausdruck mit ALL leifert TRUE, wenn:

* der Vergleich mit allen Zeilen des Subqueries erfüllt ist
* das Subquery keine Zeilen liefert
sonst FALSE

Ausdruck mit ANY leifert FALSE, wenn:

* der Vergleich mit keiner Zeilen des Subqueries erfüllt ist
* das Subquery keine Zeilen liefert
sonst TRUE

==== Vergeleich:
IN (subquery) <-> = ANY (subquery)
NOT IN (subquery) <-> <> ALL (subquery)

==== Bsp: Ausgabe von playerno, name der Spieler, year_of_birt des ältesten Spielers

[source,sql]
----
select playerno, name, year_of_birth from players where year_of_birth <= All(select year_of_birth from players);
--oder
select playerno, name, year_of_birth from players where year_of_birth = (select min(year_of_birth) from players);
----

=== Operator EXISTS

==== Syntax:

[source,sql]
----
[NOT] exists (subquery);
----

==== Hinweis:

Ausdruck liefert TRUE, wenn:

* die Subquerie mindestens eine Zeiel liefert
sonst immer FALSE

IMPORTANT: ENDE TEST STOFF